before_script:
  - source .ci/setup.sh
  - source activate loihi
  - pip install --upgrade --no-deps -e .

static_checks:
  stage: test
  script:
    - flake8 nengo_loihi examples && pylint nengo_loihi examples

tests:
  stage: test
  script:
    - pytest nengo_loihi
