before_script:
  - .ci/setup.sh
  - source activate loihi
  - pip install --upgrade --no-deps -e .

static_checks:
  stage: test
  script:
    - flake8 nengo_loihi examples && pylint nengo_loihi examples

tests:
  stage: test
  script:
    - pytest nengo_loihi

compile:
  stage: deploy
  only:
    - master
  script:
    - source .ci/compile.sh setup
    - source .ci/compile.sh run
    - source .ci/compile.sh deploy
