before_script:
  - pip3 install --user --upgrade pip
  - pip install --user --upgrade flake8 pylint pytest
  - pip install --user --upgrade -e .

static_checks:
  script:
    - flake8 nengo_loihi examples && pylint nengo_loihi examples

tests:
  script:
    - pytest nengo_loihi
